SET CHARACTER_SET_CLIENT = utf8;
SET CHARACTER_SET_CONNECTION = utf8;

CREATE TABLE `account_statement` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `statement_code` varchar(15) NOT NULL COMMENT '勘定日の和暦を西暦にした年4桁+照会番号',
  `reference_number` varchar(8) NOT NULL COMMENT '照会番号',
  `accounting_date` varchar(8) NOT NULL COMMENT '勘定日(西暦),YYYYMMDD',
  `statement_date` varchar(8) NOT NULL COMMENT '預入・払出日(西暦),YYYYMMDD',
  `jp_era` varchar(15) NOT NULL COMMENT '和暦元号',
  `accounting_date_jp` varchar(6) NOT NULL COMMENT '勘定日(和暦),YYMMDD',
  `statement_date_jp` varchar(6) NOT NULL COMMENT '預入・払出日(和暦),YYMMDD',
  `statement_type` int(1) NOT NULL COMMENT '入払区分;1:入金,2:出金,※取引区分(transaction_type)が「19:訂正」の場合入金訂正の場合は「1:出金」出金訂正の場合は「2:入金」',
  `transaction_type` int(2) DEFAULT NULL COMMENT '取引区分;default:null,10:現金,11:振込,12:他店券入金,13:交換,14:振替,15:継続,18:その他,19:訂正',
  `transaction_amount` decimal(12,0) NOT NULL COMMENT '取引金額',
  `other_bank_amount` decimal(12,0) NOT NULL COMMENT 'うち他店券金額',
  `exchange_date` varchar(6) DEFAULT NULL COMMENT '交換呈示日;YYMMDD(和暦,月,年)',
  `unpaid_return_date` varchar(6) DEFAULT NULL COMMENT '不渡返還日;YYMMDD(和暦,月,年)',
  `bill_check_type` int(1) DEFAULT NULL COMMENT '手形・小切手区分;1:小切手,2:約束手形,3:為替手形',
  `bill_check_number` varchar(7) DEFAULT NULL COMMENT '手形・小切手番号',
  `group_store_number` varchar(3) DEFAULT NULL COMMENT '僚店番号',
  `requester_code` varchar(10) DEFAULT NULL COMMENT '払込依頼人コード',
  `opposite_party_info` varchar(48) DEFAULT NULL COMMENT '払込依頼人または契約者番号;入払区分(statement_type)が1(入金)の場合,振込依頼人名,2(出金)の場合、口座振替の需要家番号(左20桁)あるいは収納企業名',
  `opposite_party_bank` varchar(15) DEFAULT NULL COMMENT '仕向銀行名',
  `opposite_party_bank_branch` varchar(15) DEFAULT NULL COMMENT '仕向支店名',
  `remark` varchar(20) DEFAULT NULL COMMENT '摘要内容',
  `normalized_opposite_party_info` varchar(100) DEFAULT NULL COMMENT '検索用に正規化されたopposite_party_info',
  `normalized_opposite_party_bank` varchar(100) DEFAULT NULL COMMENT '検索用に正規化されたopposite_party_bank',
  `normalized_opposite_party_bank_branch` varchar(100) DEFAULT NULL COMMENT '検索用に正規化されたopposite_party_bank_branch',
  `normalized_remark` varchar(100) DEFAULT NULL COMMENT '検索用に正規化されたremark',
  `edi_info` varchar(21) DEFAULT NULL COMMENT 'EDI情報',
  `note` text NOT NULL COMMENT '入出金メモ',
  `status` int(4) DEFAULT NULL COMMENT '未定',
  `journal_status` int(4) NOT NULL,
  `upload_file` varchar(23) NOT NULL COMMENT 'Cloud Storage にuploadされたcsvファイルの名前,”YYYY-MM-DD_HH-MM-SS.csv”で23字',
  `adjustment_amount` decimal(12,0) NOT NULL DEFAULT '0',
  `refund_amount` decimal(12,0) NOT NULL DEFAULT '0',
  `commission_amount` decimal(12,0) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `statement_code_UNIQUE` (`statement_code`),
  KEY `accounting_date_INDEX` (`accounting_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;