SET CHARACTER_SET_CLIENT = utf8;
SET CHARACTER_SET_CONNECTION = utf8;

CREATE TABLE `parking_invoice_d` (
  `pi_id` int(11) NOT NULL AUTO_INCREMENT,
  `pi_status` int(11) NOT NULL DEFAULT '1',
  `pi_contract_p_id1` int(11) DEFAULT NULL,
  `pi_contract_car1` varchar(255) DEFAULT NULL,
  `contracted_hire1` int(10) unsigned DEFAULT NULL,
  `pi_contract_p_id2` int(11) DEFAULT NULL,
  `pi_contract_car2` varchar(255) DEFAULT NULL,
  `contracted_hire2` int(10) unsigned DEFAULT NULL,
  `pi_contract_p_id3` int(11) DEFAULT NULL,
  `pi_contract_car3` varchar(255) DEFAULT NULL,
  `contracted_hire3` int(10) unsigned DEFAULT NULL,
  `pi_target_type` int(11) NOT NULL DEFAULT '1',
  `pi_user_class` int(11) NOT NULL DEFAULT '-1',
  `pi_company_name` varchar(255) DEFAULT NULL,
  `pi_company_name_ext` int(1) NOT NULL DEFAULT '0',
  `pi_cn_print_flag` int(11) NOT NULL DEFAULT '1',
  `pi_company_post_name` varchar(255) DEFAULT NULL,
  `pi_rep_name` varchar(255) DEFAULT NULL,
  `pi_rep_name_ext` int(1) NOT NULL DEFAULT '0',
  `pi_rn_print_flag` int(11) NOT NULL DEFAULT '1',
  `pi_address` varchar(255) DEFAULT NULL,
  `pi_address_building` varchar(255) DEFAULT NULL,
  `pi_zip_code1` varchar(3) DEFAULT NULL,
  `pi_zip_code2` varchar(4) DEFAULT NULL,
  `pi_sales_type1` int(2) NOT NULL DEFAULT '0',
  `pi_sales_title1` varchar(50) DEFAULT NULL,
  `pi_sales_price1` int(11) NOT NULL DEFAULT '0',
  `pi_sales_tax_flag1` int(1) NOT NULL DEFAULT '1',
  `pi_sales_num1` int(11) NOT NULL DEFAULT '0',
  `pi_sales_added_flag1` int(1) NOT NULL DEFAULT '1',
  `pi_sales_comment1` text,
  `pi_sales_record_year1` int(4) unsigned DEFAULT NULL,
  `pi_sales_record_month1` int(2) unsigned DEFAULT NULL,
  `pi_sales_type2` int(2) NOT NULL DEFAULT '0',
  `pi_sales_title2` varchar(50) DEFAULT NULL,
  `pi_sales_price2` int(11) NOT NULL DEFAULT '0',
  `pi_sales_tax_flag2` int(1) NOT NULL DEFAULT '1',
  `pi_sales_num2` int(11) NOT NULL DEFAULT '0',
  `pi_sales_added_flag2` int(1) NOT NULL DEFAULT '1',
  `pi_sales_comment2` text,
  `pi_sales_record_year2` int(4) unsigned DEFAULT NULL,
  `pi_sales_record_month2` int(2) unsigned DEFAULT NULL,
  `pi_sales_type3` int(2) NOT NULL DEFAULT '0',
  `pi_sales_title3` varchar(50) DEFAULT NULL,
  `pi_sales_price3` int(11) NOT NULL DEFAULT '0',
  `pi_sales_tax_flag3` int(1) NOT NULL DEFAULT '1',
  `pi_sales_num3` int(11) NOT NULL DEFAULT '0',
  `pi_sales_added_flag3` int(1) NOT NULL DEFAULT '1',
  `pi_sales_comment3` text,
  `pi_sales_record_year3` int(4) unsigned DEFAULT NULL,
  `pi_sales_record_month3` int(2) unsigned DEFAULT NULL,
  `pi_sales_type4` int(2) NOT NULL DEFAULT '0',
  `pi_sales_title4` varchar(50) DEFAULT NULL,
  `pi_sales_price4` int(11) NOT NULL DEFAULT '0',
  `pi_sales_tax_flag4` int(1) NOT NULL DEFAULT '1',
  `pi_sales_num4` int(11) NOT NULL DEFAULT '0',
  `pi_sales_added_flag4` int(1) NOT NULL DEFAULT '1',
  `pi_sales_comment4` text,
  `pi_sales_record_year4` int(4) unsigned DEFAULT NULL,
  `pi_sales_record_month4` int(2) unsigned DEFAULT NULL,
  `pi_sales_type5` int(2) NOT NULL DEFAULT '0',
  `pi_sales_title5` varchar(50) DEFAULT NULL,
  `pi_sales_price5` int(11) NOT NULL DEFAULT '0',
  `pi_sales_tax_flag5` int(1) NOT NULL DEFAULT '1',
  `pi_sales_num5` int(11) NOT NULL DEFAULT '0',
  `pi_sales_added_flag5` int(1) NOT NULL DEFAULT '1',
  `pi_sales_comment5` text,
  `pi_sales_record_year5` int(4) unsigned DEFAULT NULL,
  `pi_sales_record_month5` int(2) unsigned DEFAULT NULL,
  `pi_sales_type6` int(2) NOT NULL DEFAULT '0',
  `pi_sales_title6` varchar(50) DEFAULT NULL,
  `pi_sales_price6` int(11) NOT NULL DEFAULT '0',
  `pi_sales_tax_flag6` int(1) NOT NULL DEFAULT '1',
  `pi_sales_num6` int(11) NOT NULL DEFAULT '0',
  `pi_sales_added_flag6` int(1) NOT NULL DEFAULT '1',
  `pi_sales_comment6` text,
  `pi_sales_record_year6` int(4) unsigned DEFAULT NULL,
  `pi_sales_record_month6` int(2) unsigned DEFAULT NULL,
  `pi_sales_type7` int(2) NOT NULL DEFAULT '0',
  `pi_sales_title7` varchar(50) DEFAULT NULL,
  `pi_sales_price7` int(11) NOT NULL DEFAULT '0',
  `pi_sales_tax_flag7` int(1) NOT NULL DEFAULT '1',
  `pi_sales_num7` int(11) NOT NULL DEFAULT '0',
  `pi_sales_added_flag7` int(1) NOT NULL DEFAULT '1',
  `pi_sales_comment7` text,
  `pi_sales_record_year7` int(4) unsigned DEFAULT NULL,
  `pi_sales_record_month7` int(2) unsigned DEFAULT NULL,
  `pi_deposit_type` int(1) NOT NULL DEFAULT '0',
  `pi_deposit` int(11) NOT NULL DEFAULT '0',
  `pi_price_adjustment` int(11) NOT NULL DEFAULT '0',
  `pi_my_company` int(11) NOT NULL DEFAULT '0',
  `pi_issue_date` date DEFAULT NULL,
  `pi_limit_date` date DEFAULT NULL,
  `pi_contract_date` date DEFAULT NULL,
  `pi_payment_date` date DEFAULT NULL,
  `agreement_date` date DEFAULT NULL,
  `storage_location_certificate_shipping_date` date DEFAULT NULL,
  `pi_added_sales_year` int(4) DEFAULT NULL,
  `pi_added_sales_month` int(2) DEFAULT NULL,
  `pi_amount_billed_adjustment` int(1) NOT NULL DEFAULT '0',
  `pi_comment` text,
  `pi_memo` text,
  `pi_c_id` int(11) NOT NULL DEFAULT '0',
  `pi_mu_id` int(11) NOT NULL DEFAULT '0',
  `pi_update_datetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `pi_regist_datetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `tax_type` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`pi_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;