CREATE TABLE `sublease_d` (
  `s_id` int(11) NOT NULL AUTO_INCREMENT,
  `p_id` int(11) DEFAULT NULL,
  `o_id` int(11) DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `attribution` tinyint(4) NOT NULL DEFAULT '0',
  `type` tinyint(2) NOT NULL DEFAULT '0',
  `management_company_id` int(10) unsigned DEFAULT NULL,
  `sublease_start_date` date DEFAULT NULL,
  `sublease_end_date` date DEFAULT NULL,
  `payment_start_date` date DEFAULT NULL,
  `payment_deposit` int(11) DEFAULT NULL,
  `car_room_price_normal` int(11) DEFAULT NULL,
  `car_room_price_large` int(11) DEFAULT NULL,
  `car_room_price_highroof` int(11) DEFAULT NULL,
  `car_room_price_plane` int(11) DEFAULT NULL,
  `memo` text,
  `update_user_id` int(11) DEFAULT NULL,
  `update_datetime` datetime DEFAULT NULL,
  `regist_user_id` int(11) DEFAULT NULL,
  `regist_datetime` datetime DEFAULT NULL,
  `person_in_charge_of_property` int(11) unsigned NOT NULL DEFAULT '0',
  `person_in_charge_of_entrusted` int(11) unsigned NOT NULL DEFAULT '0',
  `person_in_charge_of_client` int(11) unsigned NOT NULL DEFAULT '0',
  `contract_attribute` int(11) unsigned NOT NULL DEFAULT '0',
  `notes_on_use` text,
  `notes_on_operation_method` text,
  `contract_item_status` tinyint(1) NOT NULL DEFAULT '0',
  `issue_fee_list` json DEFAULT NULL,
  `special_treaty` json DEFAULT NULL,
  `contract_terms` json DEFAULT NULL,
  PRIMARY KEY (`s_id`),
  KEY `idx1_sublease_d` (`p_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1523 DEFAULT CHARSET=utf8