CREATE TABLE `sublease_rent_guarantee_payment_information` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sublease_id` int(11) NOT NULL,
  `data_type` int(11) DEFAULT NULL COMMENT 'データ区分',
  `bank_code` int(5) DEFAULT NULL COMMENT '銀行コード',
  `bank_name` varchar(50) DEFAULT NULL COMMENT '銀行名',
  `bank_name_kana` varchar(50) NOT NULL COMMENT '銀行名(カナ)',
  `branch_code` int(4) DEFAULT NULL COMMENT '支店コード',
  `branch_name` varchar(50) DEFAULT NULL COMMENT '支店名',
  `branch_name_kana` varchar(50) NOT NULL COMMENT '支店名(カナ)',
  `bill_exchange_number` int(4) DEFAULT NULL COMMENT '手形交換所番号',
  `account_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '口座種別・科目',
  `account_number` int(11) DEFAULT NULL COMMENT '口座番号',
  `recipient_name` varchar(256) DEFAULT NULL COMMENT '受取人名',
  `recipient_name_kana` varchar(256) NOT NULL COMMENT '受取人名(カナ)',
  `accounting_method` tinyint(4) DEFAULT '0' COMMENT '計上方法',
  `calculation_method` tinyint(4) DEFAULT '0' COMMENT '支払額の計算方法',
  `outsourcing_fee` decimal(12,0) DEFAULT NULL COMMENT '業務委託費',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_payment_info_sublease_id__s_id` (`sublease_id`),
  CONSTRAINT `fk_payment_info_sublease_id__s_id` FOREIGN KEY (`sublease_id`) REFERENCES `sublease_d` (`s_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8
