SET CHARACTER_SET_CLIENT = utf8;
SET CHARACTER_SET_CONNECTION = utf8;

CREATE TABLE `ps_contact_log` (
  `c_id` int(11) NOT NULL AUTO_INCREMENT,
  `c_status` int(11) NOT NULL DEFAULT '0',
  `marketing_strategy` int(11) NOT NULL DEFAULT '0',
  `p_ids` varchar(255) NOT NULL,
  `personal_id` varchar(255) DEFAULT NULL,
  `user_class` int(11) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `user_name` varchar(255) DEFAULT NULL,
  `zip` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `mail` varchar(255) DEFAULT NULL,
  `tel` varchar(255) DEFAULT NULL,
  `tel2` varchar(255) DEFAULT NULL,
  `fax` varchar(255) DEFAULT NULL,
  `search_area` varchar(255) DEFAULT NULL,
  `search_lat` double NOT NULL DEFAULT '0',
  `search_lon` double NOT NULL DEFAULT '0',
  `search_min` int(11) DEFAULT NULL,
  `search_area_org` varchar(255) DEFAULT NULL,
  `search_min_org` int(11) DEFAULT NULL,
  `pref_code` int(2) NOT NULL DEFAULT '0',
  `city_code` int(5) NOT NULL DEFAULT '0',
  `region_code` int(9) NOT NULL DEFAULT '0',
  `car_model` varchar(255) DEFAULT NULL,
  `search_reason` int(11) DEFAULT NULL,
  `use_num` int(11) DEFAULT NULL,
  `use_timing` varchar(255) DEFAULT NULL,
  `comment` text,
  `memo` text,
  `concrete_schedule` date DEFAULT NULL,
  `maximun_of_budget` int(11) NOT NULL DEFAULT '0',
  `wish_of_roof` tinyint(1) NOT NULL DEFAULT '0',
  `priority_of_conditions` tinyint(1) NOT NULL DEFAULT '0',
  `is_moved` tinyint(1) NOT NULL DEFAULT '0',
  `building_has_parking` tinyint(1) NOT NULL DEFAULT '0',
  `is_bought` tinyint(1) NOT NULL DEFAULT '0',
  `car_is_decided` tinyint(1) NOT NULL DEFAULT '0',
  `necessity_of_certification` tinyint(1) NOT NULL DEFAULT '0',
  `c_mu_id` int(11) DEFAULT NULL,
  `c_datetime` datetime DEFAULT NULL,
  `c_update_datetime` datetime DEFAULT NULL,
  `c_same_id` int(11) DEFAULT NULL,
  `c_from_site` int(11) NOT NULL DEFAULT '-1',
  `c_passed_site` int(11) NOT NULL DEFAULT '0',
  `c_work_state` int(11) NOT NULL DEFAULT '0',
  `contact_contact_id` int(11) DEFAULT NULL,
  `car_model_id` int(11) DEFAULT NULL,
  `accepted_by` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`c_id`)
) ENGINE=InnoDB AUTO_INCREMENT=542598 DEFAULT CHARSET=utf8;
