--
-- Table structure for table `location_parking`
--

CREATE TABLE `location_parking` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lat` decimal(24,20) NOT NULL,
  `lng` decimal(24,20) NOT NULL,
  `status` int(11) NOT NULL,
  `parking_type` int(10) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `address` varchar(255) NOT NULL,
  `address_view` varchar(255) NOT NULL,
  `capacity` int(11) NOT NULL,
  `special_instruction` longtext NOT NULL,
  `corp_limited` int(11) DEFAULT NULL,
  `is_noticed_about_cancel` tinyint(1) NOT NULL,
  `retention_corp` int(11) DEFAULT NULL,
  `created_from` int(11) NOT NULL,
  `source_type` int(11) NOT NULL,
  `is_public_about_hire` tinyint(1) NOT NULL,
  `negotiation_about_hire` int(11) NOT NULL,
  `has_division_drawing` tinyint(1) NOT NULL,
  `can_search_by_address` tinyint(1) NOT NULL,
  `has_appointment_for_sublease` tinyint(1) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `hire_updated_at` datetime DEFAULT NULL,
  `space_updated_at` datetime DEFAULT NULL,
  `private_memo_id` int(11) DEFAULT NULL,
  `payment_id` int(11) NOT NULL,
  `income_for_agency_id` int(11) NOT NULL,
  `comment_id` int(11) DEFAULT NULL,
  `available_time_range_id` int(11) NOT NULL,
  `strage_document_id` int(11) NOT NULL,
  `management_of_azoom_side_id` int(11) DEFAULT NULL,
  `last_updated_by_id` int(11) DEFAULT NULL,
  `same_parking_id` int(11) DEFAULT NULL,
  `city_id` int(11) DEFAULT NULL,
  `region_id` int(11) DEFAULT NULL,
  `created_by_id` int(11) DEFAULT NULL,
  `use_record_in_short_term` int(11) NOT NULL,
  `name_prefix` varchar(255) NOT NULL,
  `owner_contact_id` int(11) DEFAULT NULL,
  `management_contact_id` int(11) DEFAULT NULL,
  `rentable_for_outside` int(11) NOT NULL,
  `is_important_for_marketing` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `payment_id` (`payment_id`),
  UNIQUE KEY `income_for_agency_id` (`income_for_agency_id`),
  UNIQUE KEY `available_time_range_id` (`available_time_range_id`),
  UNIQUE KEY `strage_document_id` (`strage_document_id`),
  UNIQUE KEY `private_memo_id` (`private_memo_id`),
  UNIQUE KEY `comment_id` (`comment_id`),
  KEY `location_parking_status_5ae589e21bf662e5` (`status`,`lat`,`lng`),
  KEY `location_parking_260bb888` (`management_of_azoom_side_id`),
  KEY `location_parking_410a79ac` (`last_updated_by_id`),
  KEY `location_parking_28ac141f` (`same_parking_id`),
  KEY `location_parking_b376980e` (`city_id`),
  KEY `location_parking_55a4ce96` (`region_id`),
  KEY `location_parking_0c98d849` (`created_by_id`),
  KEY `location_parking_9acb4454` (`status`),
  KEY `location_parking_b9266fc3` (`owner_contact_id`),
  KEY `location_parking_bb3b0437` (`management_contact_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1093799 DEFAULT CHARSET=utf8;
