CREATE TABLE `sublease_user_contract_d` (
  `suc_id` int(11) NOT NULL AUTO_INCREMENT,
  `su_id` int(11) DEFAULT NULL,
  `cr_id` int(11) DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT '1',
  `rent` int(11) DEFAULT NULL,
  `deposit` int(11) NOT NULL DEFAULT '0',
  `contract_year` int(4) NOT NULL DEFAULT '0',
  `contract_month` int(2) NOT NULL DEFAULT '0',
  `contract_start_date` date DEFAULT NULL,
  `contract_end_date` date DEFAULT NULL,
  `rent_start_date` date DEFAULT NULL,
  `storage_document_needs` int(11) NOT NULL DEFAULT '0',
  `daily_payment` int(11) NOT NULL DEFAULT '0',
  `daily_rent` int(11) DEFAULT NULL,
  `car_maker` int(11) DEFAULT NULL,
  `car_model` varchar(255) DEFAULT NULL,
  `car_number` varchar(255) DEFAULT NULL,
  `car_number1` varchar(10) DEFAULT NULL,
  `car_number2` varchar(10) DEFAULT NULL,
  `car_number3` varchar(10) DEFAULT NULL,
  `car_number4` varchar(10) DEFAULT NULL,
  `car_color` int(11) DEFAULT NULL,
  `contract_rep` int(11) DEFAULT NULL,
  `payment` int(10) unsigned NOT NULL DEFAULT '0',
  `payment_memo` text,
  `automatic_issue_of_invoice` tinyint(1) NOT NULL DEFAULT '0',
  `address` varchar(255) DEFAULT NULL,
  `lat` double NOT NULL DEFAULT '0',
  `lng` double NOT NULL DEFAULT '0',
  `distance_to_parking` int(6) DEFAULT NULL,
  `walk_minute_to_parking` int(4) DEFAULT NULL,
  `update_datetime` datetime DEFAULT NULL,
  `regist_datetime` datetime DEFAULT NULL,
  `created_user_id` int(10) unsigned DEFAULT NULL,
  `approved_user_id` int(10) unsigned DEFAULT NULL,
  `approved_datetime` datetime DEFAULT NULL,
  `is_short_term_use` tinyint(1) NOT NULL DEFAULT '0',
  `is_stage_rent` tinyint(1) NOT NULL DEFAULT '0',
  `stage_rent` int(11) DEFAULT NULL,
  `stage_rent_end_date` date DEFAULT NULL,
  `presence_of_renewal_fee` tinyint(1) NOT NULL DEFAULT '0',
  `month_to_renew_contract` tinyint(2) DEFAULT NULL,
  `presence_of_penalty_fee` tinyint(1) NOT NULL DEFAULT '0',
  `penalty_fee` int(11) DEFAULT NULL,
  `deposit_payment_date` date DEFAULT NULL,
  `deposit_payment_date_updated_user_id` int(10) unsigned DEFAULT NULL,
  `deposit_withdrawal_date` date DEFAULT NULL,
  `deposit_withdrawal_date_updated_user_id` int(10) unsigned DEFAULT NULL,
  `aplus_customer_number` varchar(20) DEFAULT NULL,
  `memo` text,
  `type_of_cancellation_setting` tinyint(2) NOT NULL DEFAULT '0',
  `cancellation_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`suc_id`),
  KEY `idx_sublease_user_contract_d_cr_id` (`cr_id`)
) ENGINE=InnoDB AUTO_INCREMENT=17166 DEFAULT CHARSET=utf8;
