CREATE TABLE `location_space` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `is_visible` tinyint(1) NOT NULL,
  `total_empty_rooms` int(10) unsigned NOT NULL,
  `hire` int(10) unsigned NOT NULL,
  `facility` int(11) NOT NULL,
  `setting_type` int(11) NOT NULL,
  `is_available_for_small_cars` tinyint(1) NOT NULL,
  `is_available_for_middle_cars` tinyint(1) NOT NULL,
  `is_available_for_large_cars` tinyint(1) NOT NULL,
  `is_available_for_middle_roof_cars` tinyint(1) NOT NULL,
  `is_available_for_high_roof_cars` tinyint(1) NOT NULL,
  `parking_id` int(11) NOT NULL,
  `size_id` int(11) NOT NULL,
  `is_ignore_for_aggregate_markets_hire` tinyint(1) NOT NULL,
  `capacity` int(11) NOT NULL,
  `hire_min` int(10) unsigned DEFAULT NULL,
  `roof_type` int(11) DEFAULT NULL,
  `hire_tax_class` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `space_type` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `size_id` (`size_id`),
  KEY `location_space_658dfd17` (`is_visible`),
  KEY `location_space_a2a4ca6d` (`parking_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
